### ISSUE TITLE
Promoter Sequences

### ISSUE THREAD

**Issue by Ramkyeri** [CJ-Chen/TBtools-II#55]
I have both the Gene GFF file and the genome file available and would now like to proceed with identifying promoter sequences for forward genes and reverse genes.  

https://zhuanlan.zhihu.com/p/647041818
But I wounder about + and - strand

with regards

**Comment by CJ-Chen** [comment]
the GXF Sequence Extract funtion will handle the strand of gene automatically.

**Comment by Ramkyeri** [comment]
Thank you Chen
