### ISSUE TITLE
TBtool 奶牛快穿失效。

### ISSUE THREAD

**Issue by HotNewMike** [CJ-Chen/TBtools-II#57]

**Comment by CJ-Chen** [comment]
哪个链接？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月23日(周二) 下午4:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [CJ-Chen/TBtools-II] TBtool 奶牛快穿失效。 (Issue #57)

**Comment by Revolution233** [comment]
> 哪个链接？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年1月23日(周二) 下午4:30 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [CJ-Chen/TBtools-II] TBtool 奶牛快穿失效。 (Issue #57) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

https://www.yuque.com/cjchen/hirv8i/iclxpx2841g205hm
https://tbtools.cowtransfer.com/s/fd65f874240044

**Comment by CJ-Chen** [comment]
Fixed!

**Comment by CJ-Chen** [comment]
Fixed!
