### ISSUE TITLE
Could not create the Java Virtual Machine

### ISSUE THREAD

**Issue by pk-zhu** [CJ-Chen/TBtools-II#61]
It seems like there's an issue with running the command. Even after switching Java versions, the problem persists. Here's the issue:

$ java -jare TBtools_JRE1.6.jar Fasta
Unrecognized option: -jare
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

$ java --version
openjdk 22.0.1-internal 2024-04-16
OpenJDK Runtime Environment (build 22.0.1-internal-adhoc.conda.src)
OpenJDK 64-Bit Server VM (build 22.0.1-internal-adhoc.conda.src, mixed mode, sharing)

However, TBtools functions properly with commands like：

$ java -cp TBtools_JRE1.6.jar biocjava.bioIO.FastX.FastaIndex.QuickStatFasta 
[Usage]:
        --inFasta       Set input fasta file [Required]
        --outPutFile    Set output Stat file [Default:NO]

Could you please provide guidance on resolving this issue? Thank you.

**Comment by ChIPseq** [comment]
Did you resolved this issue? I have same issue like this.

**Comment by pk-zhu** [comment]
Yes. ```java -jare``` is a typo. It should be ```java -jar```  to execute.

**Comment by ChIPseq** [comment]
thanks for you answer
