### ISSUE TITLE
CDD及蛋白提取，软件似乎有问题

### ISSUE THREAD

**Issue by LXN628** [CJ-Chen/TBtools-II#64]
问题一：当我用CDD网站得到CDD.txt后，进入可视化界面，输入了CDD.txt以及基因组蛋白文件，出来的是一团黑色的看不清楚的图。（我用以前旧的版本不会出现这个问题，可惜旧版本被我更新了）。
问题二：蛋白理化性质的提取，用protein那里的功能可以一键提取，旧版本不会出问题，新版本只给了稳定指数，其他参数都是null

**Comment by CJ-Chen** [comment]
第一个问题没遇到过
第二个问题，请更新到最新版本。这是由于对方网站的渲染代码调整了。
「BioAnno」问答社区，源于「TBtools技能易物群」，将「问有所答，答有所获」的理念贯彻到底.
有问题就有答案：请应答者喝一杯咖啡，让付出产生实在的反馈；
提供高质量答案就有收获：进行自我能力的价值实现。
TB币可微信提现，可兑换等值服务如chatGPT Tokens，
https://www.bioanno.com/ 欢迎到「BioAnno」社区解决你的问题，并帮助其他人解决他们的问题。
PS：不局限于 TBtools~
