### ISSUE TITLE
关于seqlogo自定义字符的问题

### ISSUE THREAD

**Issue by weiydcn** [CJ-Chen/TBtools-II#65]
陈老师：
   您好! 由于我想分析3个核酸对的保守性，因此想用字符替代3核酸，这样就需要64个字符，我想用小写英文字符也加进去来表示。但是好像软件都会默认把小写字符变为大写字符，甚至用希腊文的α，也会变成A，能否保留字符原来的样子，谢谢？

**Comment by CJ-Chen** [comment]
嗯，小写字母没计划支持。如果用 N 能解决，则考虑用N
