### ISSUE TITLE
有一个特定场景的生物需求，请问大佬可以给个联系方式吗

### ISSUE THREAD

**Issue by Lbaiall** [CJ-Chen/TBtools-II#68]
感谢！

**Comment by CJ-Chen** [comment]
可以整理好需求后给我一个邮件，微信 CJ-Chen-0410，不过如果这个需求我用不上，或许不会开发哈。哈哈，我基本只开发我觉得我用得上的功能。
120509419
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2024年11月4日 ***@***.***>***@***.***>主题[CJ-Chen/TBtools-II] 有一个特定场景的生物需求，请问大佬可以给个联系方式吗 (Issue #68)
感谢！

**Comment by Lbaiall** [comment]
好的！非常感谢
