### ISSUE TITLE
共线性分析没有生成.CTL后缀文件

### ISSUE THREAD

**Issue by wyl1219** [CJ-Chen/TBtools-II#69]
陈老师，您好。
我想请教下，我用tbtools做基因组内共线性分析，结果文件里没有生成ctl文件，有可能是什么原因呢，我换了几组基因和注释文件，依然有相同问题，麻烦您帮忙解答下，谢谢。

**Comment by CJ-Chen** [comment]
「BioAnno」问答社区，源于「TBtools技能易物群」，将「问有所答，答有所获」的理念贯彻到底.
有问题就有答案：请应答者喝一杯咖啡，让付出产生实在的反馈；
提供高质量答案就有收获：进行自我能力的价值实现。
TB币可微信提现，可兑换等值服务如chatGPT Tokens，
https://www.bioanno.com/ 欢迎到「BioAnno」社区解决你的问题，并帮助其他人解决他们的问题。
PS：不局限于 TBtools~
