### ISSUE TITLE
软件运行错误

### ISSUE THREAD

**Issue by 820937834** [CJ-Chen/TBtools-II#70]
In international mode, an error will be reported whenever any module of the software is run. 

error log:
"[StdErr]: Curr log file:C:\Users\scott\AppData\Local\Temp\TBtools.7882674659784173801.20241217142612.log
[StdErr]: [Debug...All Standard Error Info will show as following:...]
[StdErr]: Curr log file:C:\Users\scott\AppData\Local\Temp\TBtools.7882674659784173801.20241217142612.log
[StdErr]: Curr java version:11.0.6
[StdErr]: Curr TBtools version:2.146
[StdErr]: Maxmum Memory for Curr TBtools: 4246732800
[StdErr]: Size:java.awt.Dimension[width=170,height=47]
[StdErr]: curVersion:2.142:force
[StdErr]: Fetch Location:200
[StdErr]: Factor(>0.6):0.7476497105947247
[StdOut]: JBrowser Not Available. Use Local WebBrowser.
[StdErr]: 2024-12-17 14:26:15:Update Splash Failed. Never mind.
[StdErr]: BlastZone dbdir created.
[StdErr]: Auto Decide dbdir: C:\Users\scott\.TBtools\.BlastZone\.db
[StdErr]: bzdd.dbFile:C:\Users\scott\.TBtools\.BlastZone\.db
[StdErr]: 2024-12-17 14:26:27:Prepare CreateShortCutLnk:biocjava.bioDoer.BLAST.BlastZone.GUI.BlastZoneGUIPanel
[StdErr]: 12月 17, 2024 2:26:35 下午 biocjava.GUIexcutors.TBtools$32 actionPerformed
[StdErr]: 严重: null
[StdErr]: java.lang.reflect.InvocationTargetException
[StdErr]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[StdErr]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[StdErr]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[StdErr]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[StdErr]: 	at biocjava.GUIexcutors.TBtools$32.actionPerformed(TBtools.java:2829)
[StdErr]: 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
[StdErr]: 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
[StdErr]: 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
[StdErr]: 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[StdErr]: 	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
[StdErr]: 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
[StdErr]: 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
[StdErr]: 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
[StdErr]: 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
[StdErr]: 	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
[StdErr]: 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
[StdErr]: 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
[StdErr]: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
[StdErr]: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
[StdErr]: 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
[StdErr]: 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
[StdErr]: 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
[StdErr]: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
[StdErr]: 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
[StdErr]: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
[StdErr]: 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
[StdErr]: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
[StdErr]: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
[StdErr]: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[StdErr]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[StdErr]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
[StdErr]: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[StdErr]: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
[StdErr]: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[StdErr]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[StdErr]: 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[StdErr]: Caused by: java.util.MissingResourceException: Can't find bundle for base name biocjava/i18n/FastaExtractorGUIPanel, locale zh_cn
[StdErr]: 	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:932)
[StdErr]: 	at biocjava.GUIexcutors.FastaExtractor.FastaExtractorGUIPanel.<init>(FastaExtractorGUIPanel.java:64)
[StdErr]: 	... 42 more
[StdErr]: 
[StdErr]: 12月 17, 2024 2:26:38 下午 biocjava.GUIexcutors.TBtools$32 actionPerformed
[StdErr]: 严重: null
[StdErr]: java.lang.reflect.InvocationTargetException
[StdErr]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[StdErr]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[StdErr]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[StdErr]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[StdErr]: 	at biocjava.GUIexcutors.TBtools$32.actionPerformed(TBtools.java:2829)
[StdErr]: 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
[StdErr]: 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
[StdErr]: 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
[StdErr]: 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[StdErr]: 	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
[StdErr]: 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
[StdErr]: 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
[StdErr]: 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
[StdErr]: 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
[StdErr]: 	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
[StdErr]: 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
[StdErr]: 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
[StdErr]: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
[StdErr]: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
[StdErr]: 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
[StdErr]: 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
[StdErr]: 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
[StdErr]: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
[StdErr]: 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
[StdErr]: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
[StdErr]: 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
[StdErr]: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
[StdErr]: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
[StdErr]: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[StdErr]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[StdErr]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
[StdErr]: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[StdErr]: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
[StdErr]: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[StdErr]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[StdErr]: 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[StdErr]: Caused by: java.util.MissingResourceException: Can't find bundle for base name biocjava/i18n/GenBank2FastaGUIPanel, locale zh_cn
[StdErr]: 	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:932)
[StdErr]: 	at biocjava.GUIexcutors.NCBIdownLoadSeqGUI.GenBank2FastaGUIPanel.<init>(GenBank2FastaGUIPanel.java:51)
[StdErr]: 	... 42 more
[StdErr]: 
[StdErr]: 12月 17, 2024 2:27:16 下午 biocjava.GUIexcutors.TBtools$32 actionPerformed
[StdErr]: 严重: null
[StdErr]: java.lang.reflect.InvocationTargetException
[StdErr]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[StdErr]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[StdErr]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[StdErr]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[StdErr]: 	at biocjava.GUIexcutors.TBtools$32.actionPerformed(TBtools.java:2829)
[StdErr]: 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
[StdErr]: 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
[StdErr]: 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
[StdErr]: 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[StdErr]: 	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
[StdErr]: 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
[StdErr]: 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
[StdErr]: 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
[StdErr]: 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
[StdErr]: 	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
[StdErr]: 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
[StdErr]: 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
[StdErr]: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
[StdErr]: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
[StdErr]: 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
[StdErr]: 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
[StdErr]: 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
[StdErr]: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
[StdErr]: 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
[StdErr]: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
[StdErr]: 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
[StdErr]: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
[StdErr]: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
[StdErr]: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[StdErr]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[StdErr]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
[StdErr]: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[StdErr]: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
[StdErr]: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[StdErr]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[StdErr]: 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[StdErr]: Caused by: java.util.MissingResourceException: Can't find bundle for base name biocjava/i18n/FastaStaterGUIPanel, locale zh_cn
[StdErr]: 	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:932)
[StdErr]: 	at biocjava.GUIexcutors.FastaExtractor.FastaStaterGUIPanel.<init>(FastaStaterGUIPanel.java:49)
[StdErr]: 	... 42 more
[StdErr]: 
[StdErr]: 12月 17, 2024 2:27:24 下午 biocjava.GUIexcutors.TBtools$32 actionPerformed
[StdErr]: 严重: null
[StdErr]: java.lang.reflect.InvocationTargetException
[StdErr]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[StdErr]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[StdErr]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[StdErr]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[StdErr]: 	at biocjava.GUIexcutors.TBtools$32.actionPerformed(TBtools.java:2829)
[StdErr]: 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
[StdErr]: 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
[StdErr]: 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
[StdErr]: 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[StdErr]: 	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
[StdErr]: 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
[StdErr]: 	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
[StdErr]: 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
[StdErr]: 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
[StdErr]: 	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
[StdErr]: 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
[StdErr]: 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
[StdErr]: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
[StdErr]: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
[StdErr]: 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
[StdErr]: 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
[StdErr]: 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
[StdErr]: 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
[StdErr]: 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
[StdErr]: 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
[StdErr]: 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
[StdErr]: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
[StdErr]: 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
[StdErr]: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[StdErr]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[StdErr]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
[StdErr]: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[StdErr]: 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
[StdErr]: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[StdErr]: 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[StdErr]: 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[StdErr]: 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[StdErr]: Caused by: java.util.MissingResourceException: Can't find bundle for base name biocjava/i18n/FastaMergeAndSplitGUIPanel, locale zh_cn
[StdErr]: 	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
[StdErr]: 	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:932)
[StdErr]: 	at biocjava.GUIexcutors.FastaExtractor.FastaMergeAndSplitGUIPanel.<init>(FastaMergeAndSplitGUIPanel.java:46)
[StdErr]: 	... 42 more
[StdErr]: 
"

**Comment by CJ-Chen** [comment]
Don't use international mode.

**Comment by 820937834** [comment]
> Don't use international mode.

好的 感谢
